const captions = [
  "Trying to look British at Tower Bridge",
  "Recreating a notorious photo of our friend Rick in Washington, DC",
  "Cutting the cake at our first suite dinner in the Trumbull Buttery",
  "When at Anchor Bar in Buffalo, NY...",
  "Post-prom power nap",
  "Perry the Platypus on Cape Cod",
  "My first photo... ever. Ft. my cousin Kyle",
  "Graduation with my vovos",
  "Fernandes fam at the White House",
  "In self defense mode after turning around to see a black bear 20 ft away",
  "Reed Dehner and I ready to take on the Travis Scott concert",
  "Trying (and failing) to look cool +28 on the 17th green",
  "On the floor of a Hummer during a Florida Uber ride down the highway",
  "Fernandes fam at the Eiffel Tower",
  "Waterpark whiplash victim in recovery",
  "Feeling tropical and looking great",
  "Splitting roles at the y/cs Gala",
  "Begrudgingly taking a photo at my first internship with Red Hat",
  "Baguette on the Eiffel Tower >>>>",
  "Couldn't tell ya",
  'Posing for the thumbnail of our Spanish podcast: "Charlas del Campus"',
  "Grill dad and soccer mom for spirit day",
  "Monkey business on Halloween",
  "Justin Bieber and Ludacris at Yale",
  "Fernandes fam at the Lincoln Memorial",
  "Senior trip in Delray Beach, FL",
  "My first time baking macarons (6 years before the first Macaron Monday)",
  "A lifesize graduation photo (don't ask why) hatefully vandalized",
  "Caught out in a downpour in downtown Fort Lauderdale",
  "Presenting our product, y/labs, at the y/cs Gala"
]

export default captions;